//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubnauticaModManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Programmes\\steamapps\\common\\Subnautica")]
        public string GamePath {
            get {
                return ((string)(this["GamePath"]));
            }
            set
            {
                this["GamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nc1Brb0Vxck51a0c1bU5KRGxHbGg5RkFCRHBSYXlEWGdNanpNU3ZnbEdPMWRQc201YVRvS1ZGSU8yWEl" +
            "mTWNuNi0tR05CN0ZMRHJBNUlrL1ZGdWZsUjhsdz09--febdeecd49139282d0b653bebd72120eebcf7" +
            "c7e\r\n")]
        public string NexusApiKey {
            get {
                return ((string)(this["NexusApiKey"]));
            }
            set {
                this["NexusApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveApiKey {
            get {
                return ((bool)(this["SaveApiKey"]));
            }
            set {
                this["SaveApiKey"] = value;
            }
        }
    }
}
